---
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.stage}-userpool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.stage}-userpoolclient
      UserPoolId:
        Ref: CognitoUserPool
      GenerateSecret: false # :: required for AWS Amplify integration
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

  CognitoGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: ${self:custom.stage}-apig-authorizer
      Type: COGNITO_USER_POOLS
      AuthorizerResultTtlInSeconds: 10
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs:
        - Fn::Join:
            - ''
            - - 'arn:aws:cognito-idp:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - ':userpool/'
              - Ref: CognitoUserPool

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: ${self:custom.stage}-identitypool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:
            Ref: CognitoUserPoolClient
          ProviderName:
            Fn::GetAtt: ['CognitoUserPool', 'ProviderName']

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: CognitoIdentityPool
      Roles:
        authenticated:
          Fn::GetAtt: [CognitoAuthRole, Arn]

  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: cognito-identity.amazonaws.com
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: CognitoIdentityPool
              ForAnyValue:StringLike:
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: 'CognitoAuthorizedPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # :: base Cognito permissions
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: '*'

              # :: allow authenticated users to actually invoke this API
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource:
                  Fn::Join:
                    - ''
                    - - 'arn:aws:execute-api:'
                      - Ref: AWS::Region
                      - ':'
                      - Ref: AWS::AccountId
                      - ':'
                      - Ref: ApiGatewayRestApi
                      - '/*'

Outputs:
  AwsRegion:
    Value:
      Ref: AWS::Region

  CognitoUserpoolId:
    Value:
      Ref: CognitoUserPool

  CognitoUserpoolClientId:
    Value:
      Ref: CognitoUserPoolClient

  CognitoIdentitypoolId:
    Value:
      Ref: CognitoIdentityPool
