# :: TODO update these roles into more specialized versions for overall security.
#
---
Resources:
  ApiEndpointsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: ${self:custom.appname}LambdaEndpoint
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # :: allows emitting to CW logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - Fn::Join:
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - 'log-group:/aws/lambda/*:*:*'

              # :: allows full access to Amazon Chime SDK operations
              - Effect: Allow
                Action:
                  - chime:CreateMeeting
                  - chime:CreateMeetingWithAttendees
                  - chime:DeleteMeeting
                  - chime:GetMeeting
                  - chime:ListMeetings
                  - chime:CreateAttendee
                  - chime:BatchCreateAttendee
                  - chime:DeleteAttendee
                  - chime:GetAttendee
                  - chime:ListAttendees
                  - chime:ListAttendeeTags
                  - chime:ListMeetingTags
                  - chime:ListTagsForResource
                  - chime:TagAttendee
                  - chime:TagMeeting
                  - chime:TagResource
                  - chime:UntagAttendee
                  - chime:UntagMeeting
                  - chime:UntagResource
                Resource: '*'

              # :: allows full access to DynamoDB datastores
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - Fn::Join:
                      - ':'
                      - - 'arn:aws:dynamodb'
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - Fn::Join:
                            - '/'
                            - - 'table'
                              - Ref: ChimeMeetingsTable
